<?php
/* @var $this Mage_Adminhtml_Block_Sales_Order_Totals_Item */
?>
<?php if($this->getSource() instanceof Mage_Sales_Model_Order){ ?>
<?php if ((float) $this->getSource()->getCreditAmountRefunded()): ?>
    <tr>
        <td class="label"><strong>客户课点退款</strong></td>
        <td><strong><?php echo $this->getSource()->getCreditAmountRefunded(); ?></strong></td>
    </tr>
<?php endif; ?>
<?php } else { ?>
<?php if ((float) $this->getSource()->getCreditAmount()): ?>
    <tr>
        <td class="label"><strong>课点退款</strong></td>
        <td><strong><?php echo $this->getSource()->getCreditAmount(); ?></strong></td>
    </tr>
<?php endif;
    //Mage_Sales_Model_Order_Creditmemo
}?>

