<?php
/* @var $this D1m_Customapi_Block_Form */
?>
<h3><?php echo $this->title;?></h3>
<form method="POST" action="<?php echo $this->action;?>">
<ul>
	<?php 
	foreach($this->attributes as $key => $val):?>
	
	<li>
	<label for="<?php echo $key;?>"><?php echo $key;?>:</label>: 
	<input type="text" id="<?php echo $key;?>" name="<?php echo $this->name;?>[<?php echo $key;?>]" value="<?php echo $val;?>"/>
	</li>
	<?php
	endforeach;?>


	<li>
		<input type="submit" name="submit" value="submit"/>
	</li>

</ul>




</form