<?php
/* @var $this  D1m_Customapi_Block_Test */
?>
<head> <meta charset="UTF-8"><title>接口测试</title></head>
<ul>
	<li>
		<a href="<?php echo $this->getUrl('customapi/testrun/searchMembersform');?>" target="_blank">会员查询接口</a>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('customapi/testrun/addMemberform');?>" target="_blank">新创建用户</a>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('customapi/testrun/updateMemberform');?>" target="_blank">修改用户</a>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('customapi/testrun/addClassOrderform');?>" target="_blank">购买课时记录接口</a>
	</li>
	<li>
		<a href="<?php echo $this->getUrl('customapi/testrun/addReserveClassform');?>" target="_blank">预定课程记录接口</a>
	</li>
</ul>