<div class="dashboard" style="background-color:#fff;padding:20px;margin-top:80px;">
	<?php if($this->getTitle()): ?>
	<div class="page-title">
	    <h1><?php echo $this->getTitle() ?></h1>
	</div>
	<?php endif; ?>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
	    <div class="fieldset">
	    <?php echo $this->getBlockHtml('formkey')?>
	    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
	    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
	        <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
	        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	        <ul class="form-list">
	            <li class="fields">
	                <?php echo $this->getNameBlockHtml() ?>
	            </li>
	            <li class="wide">
	                <label for="company"><?php echo $this->__('Company') ?></label>
	                <div class="input-box">
	                    <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
	                </div>
	            </li>
	            <li class="fields">
	                <div class="field">
	                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
	                    <div class="input-box">
	                        <input type="tel" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
	                    </div>
	                </div>
	            </li>
	        </ul>
	    </div>
	    <div class="fieldset">
	        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
	        <ul class="form-list">
	        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
	            <li class="wide">
	                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
	                <div class="input-box">
	                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
	                </div>
	            </li>
	        
	            <li class="fields">
	                <div class="field">
	                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
	                    </div>
	                </div>
	                <div class="field">
	                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
	                    <div class="input-box">
	                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
	                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
	                        </select>
	                        <script type="text/javascript">
	                        //<![CDATA[
	                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
	                        //]]>
	                        </script>
	                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
	                    </div>
	                </div>
	            </li>
	            <li class="fields">
	                <div class="field">
	                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
	                    <div class="input-box">
	                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
	                    </div>
	                </div>
	            </li>
	           <input type="hidden" name="country_id" value="CN" />
	           <input type="hidden" name="default_billing" value="1" />
	           
	        </ul>
	    </div>
	    <div class="buttons-set">
	        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	        <button type="submit" title="<?php echo $this->__('Save Address') ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
	    </div>
	</form>
	<script type="text/javascript">
	//<![CDATA[
	    var dataForm = new VarienForm('form-validate', true);
	    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	//]]>
	</script>
</div>
