<?php
/* @var $this  Robi_Checkout_Block_Pastedorderedclasses */
?>
<div class="block-item past-activities">
  <p class="t"><?php echo $this->__('已参与的课程');?></p>
  <table class="table" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <th class="th1"><?php echo $this->__('DATE');?></th>
      <th class="th2"><?php echo $this->__('TITLE');?></th>
      <th class="th3 pc"><?php echo $this->__('LOCATION');?></th>
      <th class="th4 pc"><?php echo $this->__('操作');?></th>
      <th class="th3 mobile"></th>
    </tr>
    <?php
	$orderedClses = $this->_getOrderClassesCollection();
	foreach($orderedClses as $orderedCls):
	?>
    <tr>
      <td><?php echo $this->formatDate($orderedCls->classdate);?></td>
      <td><?php echo $this->escapeHtml($orderedCls->name);?><?php // echo Mage::getSingleton('sales/order_config')->getStatusLabel($orderedCls->getOrderStatus());?></td>
      <td class="pc"><?php echo $orderedCls->product_province_label?> <?php echo $this->escapeHtml($orderedCls->product_lassaddress); // $orderedCls->product_province_label ?></td>
      <td class="pc">
          <?php
          //根据课程日期，2个月内可以下载菜谱
          $d1=new DateTime($orderedCls->classdate);
          $d1->add(new DateInterval('P2M'));
          $s1= $d1->format('Y-m-d');
          if (date("Y-m-d")<= $s1):?>
          <a class="btn" href="<?php echo $this->getUrl('course/index/download').'id/'.$orderedCls->getOrderId().'/pname/'.urlencode($orderedCls->name);?>"><?php echo $this->__('下载菜谱');?></a>
          <?php endif; ?>
      </td>
      <td class="mobile">
          <?php if (date("Y-m-d")<= $s1):?>
          <a class="btn" href="<?php echo $this->getUrl('course/index/download').'id/'.$orderedCls->getOrderId().'/pname/'.urlencode($orderedCls->name);?>"><?php echo $this->__('下载菜谱');?></a>
          <?php endif; ?>
      </td>
    </tr>
    <?php endforeach;?>
	
	<?php foreach($this->_getOrderClassesPendingCollection() as $orderedCls):?>
    <tr>
      <td><?php echo $this->formatDate($orderedCls->classdate);?></td>
      <td><?php echo $this->escapeHtml($orderedCls->name);?><?php // echo Mage::getSingleton('sales/order_config')->getStatusLabel($orderedCls->getOrderStatus());?></td>
      <td class="pc"><?php echo $orderedCls->product_province_label?> <?php echo $this->escapeHtml($orderedCls->product_lassaddress); // $orderedCls->product_province_label ?></td>
      <td class="pc">
          <?php if($orderedCls->order_status == 'pending'):?>
            <a class="btn" target="_blank" href="<?php echo $this->getUrl('checkout/cart/againPay').'oid/'.$orderedCls->getOrderId(); ?>"><?php echo $this->translateStatus($orderedCls->order_status) ?></a>
          <?php else:?>
            <span><?php echo $this->translateStatus($orderedCls->order_status) ?></span>
          <?php endif; ?>

      </td>
      <td class="mobile">
          <?php /*if($orderedCls->order_status == 'pending'):?>
            <a class="btn" target="_blank" href="<?php echo $this->getUrl('course/index/cancelorder').'id/'.$orderedCls->getOrderId(); ?>"><?php echo $this->translateStatus($orderedCls->order_status) ?></a>
          <?php else:?>
            <span><?php echo $this->translateStatus($orderedCls->order_status) ?></span>
          <?php endif;*/?>
          <span><?php echo $this->translateStatus($orderedCls->order_status) ?></span>
      </td>
    </tr>
    <?php endforeach;?>
    
  </table>
</div>