<?php
/* @var $this D1m_Course_Block_Reorder */
/* @var $oproduct  Mage_Catalog_Model_Product */
/* @var $nproduct  Mage_Catalog_Model_Product */
$oproduct=$this->getOldinfo();
$nproduct=$this->getNewinfo();
if (($oproduct==null) or ($nproduct==null)) return;
$nid=$this->getRequest()->getparam('nid',0);
settype($nid,"integer");
if ($nid<=0) return ;
?>
<form method="POST" action="<?php echo Mage::geturl('course/index/reorder3'); ?>">
<div class="reorder" style="text-align:center;color:#94712b; width: 80%; margin-top: 120px; margin-right: auto; margin-left: auto;">
    <p>订单号：<br/> <?php echo $this->order_id;?></p>
    <p>人数:   <br/> <?php echo (int)$this->order_qty;?>
    </p>
    <p>当前课程：<br/>
        <?php echo $oproduct->getName();?>
        (<?php echo substr($oproduct->getData('class_date'),0,10);?> <?php echo $oproduct->getData('n_classtime1');?>-<?php echo $oproduct->getData('n_classtime2');?>)
    </p>
    <p>想更换的课程：<br/>
        <?php echo $nproduct->getName();?>
       (<?php echo substr($nproduct->getData('class_date'),0,10);?> <?php echo $nproduct->getData('n_classtime1');?>-<?php echo $nproduct->getData('n_classtime2');?>)
    </p>
    <p>
        <input type="submit" value="确认更换" name="B1" style="background:0; border: 0px currentColor; border-image: none; color: gold;cursor: pointer" > 或
        <a style="color:gold" href="<?php  echo Mage::geturl('course/index/reorderout');?>">退出换课模式</a>
    </p>
    <input type="hidden" name="nid" value="<?php echo $nid;?>">
</div>
</form>