<h4>中国银联在线支付</h4>
<p class="descr">支持18家国内银行网上支付，需开通网上银行功能。</p>
<div class="bank-list">
	<ul class="clearfix">
		<li class="icbc"><span>中国工商银行</span></li>
		<li class="cmb"><span>招商银行</span></li>
		<li class="ccb"><span>中国建设银行</span></li>
		<li class="boc"><span>中国银行</span></li>
		<li class="abc"><span>中国农业银行</span></li>
		<li class="comm"><span>交通银行</span></li>
		<li class="spdb"><span>浦发银行</span></li>
		<li class="cgb"><span>广发银行</span></li>
		<li class="citic"><span>中信银行</span></li>
		<li class="ceb"><span>中国光大银行</span></li>
		<li class="cib"><span>兴业银行</span></li>
		<li class="sdb"><span>深圳发展银行</span></li>
		<li class="cmbc"><span>中国民生银行</span></li>
		<li class="spabank"><span>平安银行</span></li>
		<li class="shbank"><span>上海银行</span></li>
		<li class="psbc"><span>中国邮政储蓄银行</span></li>
		<li class="bjbank"><span>北京银行</span></li>
		<li class="hxb"><span>华夏银行</span></li>
	</ul>
</div>
<div class="endnote">
	<p class="tip">订单提交后将跳转到 <span>中国银联在线支付</span> 继续完成线上支付。</p>
	<p>友情提示：招行不支持Safari浏览器，中信、中行、光大只支持IE浏览器。线上支付额度按各银行规定有所不同。</p>
	<p>如果遇到问题未完成支付，进入“我的优e→订单管理”中对本订单重新支付即可。我们的客服也会及时联系您，协助完成在线支付。</p>
</div>
