<?php
$installer = $this;
$installer->startSetup();
$sql="
DROP TABLE IF EXISTS {$this->getTable('d1m_chef')};
CREATE TABLE {$this->getTable('d1m_chef')}
(
    `chef_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `cname` varchar(255) NOT NULL DEFAULT '',
    `coneword` varchar(255) NOT NULL default '',
    `cshort` text NOT NULL,
    `clong` text NOT NULL,
    `csmallpic` varchar(255) NOT NULL DEFAULT '',
    `cbigpic` varchar(255) NOT NULL DEFAULT '',
    `cregion` varchar(20) NOT NULL DEFAULT '',
    `corder` int(11) default '0',
    `cstatus` smallint(6) NOT NULL DEFAULT '1',
    PRIMARY KEY ( `chef_id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8;

insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('1','Kelvin','上海四季酒店，柏悦酒店，新天地朗廷酒店等多家奢华酒店任命为厨师长及酒店行政副总厨','双眉微微上扬，硬挺的鼻梁搭配坚定的目光，雕塑般的面孔棱角分明，站在一堆人里，都有人指出他来，问：你是日本人伐？当然是日本人里帅气的那一类。但，他不是，他是堂堂的中国精英大厨。\r\n拥有超过13年工作经历，令其在所擅长的法国、意大利、西班牙等传统西式烹饪的基础上，不断融合、创新，用无限的创意为学员制造味蕾上的不断惊喜，同时还将他的烹饪秘笈源源不断地分享给学员。\r\n来上海菲仕乐学院餐厅，和Kelvin一起，感受他和他的团队带来的美味的颤抖吧！','chef/chef/1s.jpg','chef/chef/1b.jpg','上海','1','1','冷峻威严的行政总厨');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('2','Luigi','崇明金茂凯悦  西餐厨师长\n上海柏悦酒店  厨师长\n上海金茂君悦大酒店  厨师领班','他一点没有领导的架子，对任何人都很温和。虽然没有架子，资历却非常的深厚，如果您想如果您想领略一个大厨的风范，找他是没有错的。\n如果您想跟一个精通意大利菜的人，像模像样学几道意大利菜，找他是没有错的。\n如果您想了解菲仕乐的产品，他用得相当的熟练，事无巨细。\n甚至您如果询问和烹饪无关的问题，他如果知道，都会告诉您。\n喜欢开玩笑，笑的时候有虎牙。他就是Luigi，一个很多姿多彩的人。','chef/chef/2s.jpg','chef/chef/2b.jpg','上海','2','1','多姿多彩有虎牙的人');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('3','Smith','澳门威尼斯人渡假酒店 点心部厨师长\n上海龙之梦万丽酒店 点心部厨师长\n上海缘澍餐饮有限公司  点心部厨师长','会烘焙的人有千千万万，但是他绝对是做得最好的人之一。\n因为如果你跟他学做东西，会发现他专注做事的时候，心无旁骛。\n他做的甜品好吃极了，甚至他做好的甜品，他的同事都抢着吃。他做甜品的时候，特别的细心，特别的温柔，手中的食材像是他最爱的人。\n如此做料理，怎么会不好吃。\n有时候看他做甜品的过程都是一种享受。\n你可以问问他在澳门工作的经历，那是他十分骄傲的一段，当然，菲仕乐现在是他的归宿。','chef/chef/3s.jpg','chef/chef/3b.jpg','上海','3','1','低调的华丽');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('4','Alex','暂缺','你问他，他最擅长做什么，他会说，我擅长做匹萨，各种各样的匹萨。\n其实他会很多，但是他不善言语。他的语言，都在他手头揉弄的面团里，然后放入炉火，变成那不勒斯的匹萨，让你吃一口，感觉到了那不勒斯的海边，阳光下的海风如此温柔。\n他说，他喜欢在做菜的时候有点新鲜的东西在里面，用心了解客人的喜欢吃什么口感，所以，假若您经常去菲仕乐学院餐厅，发现一个厨师会根据您的意见变换口感，那么不要奇怪，因为他喜欢观察。\n他说，他喜欢有怪的想法，喜欢平时喜欢游泳到处旅行接触品尝不同食材料理！\n他高高帅帅，相信您一定喜欢到菲仕乐学院餐厅跟他一起分享边走边吃的经历。','chef/chef/4s.jpg','chef/chef/4b.jpg','上海','4','1','专注匹萨事业若干年');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('5','Anthony','上海外高桥皇冠假日酒店 西餐厨师\n上海世贸皇家艾美酒店 厨师领班\n上海新天地郎庭酒店  厨师长','他长得有一些像林志颖，但是要阳刚得多。\n他师从意大利匹萨大师Enzo Coccia的时候，这位大师说Anthony是他遇到的最有天分的人，想把他带到意大利去，幸好他没有答应，否则你在菲仕乐学院餐厅就见不到这位英俊大厨了。\n餐桌烛光点点，明档熊熊炉火，点一个匹萨，让他当面为你烤制一个出神入化的匹萨，是在菲仕乐学院餐厅才能有的享受。\n酷爱体育，尤其喜欢在雨中踢球。有一些酷，笑的时候又感觉天都亮了。\n如果能亲临他教导，那么更是一种生活中莫大的乐趣。','chef/chef/5s.jpg','chef/chef/5b.jpg','上海','5','1','一个差点被带到意大利的明星');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('6','Johnny','外滩三号   甜品厨师\n丽星邮轮    甜品厨师长\npark hyatt 柏悦酒店  甜品部主管','他有很多刀，大大小小，都是利器，但都用在案板上。\n厨师，如果不爱刀，就好比侠客不爱他的武器。\n他用刀很犀利，如果摘下厨师帽，他的头发硬而竖，书上说，这样的男人有性格。\n如果您加他的微信一定要写明自己是什么人，他通过很谨慎，但是谨慎永远是一个优点。\n他在邮轮上和外滩三号都工作过，相信这是一段浪漫的经历，也许他并不觉得。\n但是，他做的菜好吃，这点，他和我们都知道。','chef/chef/6s.jpg','chef/chef/6b.jpg','上海','6','1','刀客一样的男人');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('7','Gorden','PARK HYATT柏悦酒店   厨师长\nTHERR ON THE BOND  厨师','从来没见过Gorden生气，总是一副好脾气的样子。\n人总得经历多，历练多，才学会不生气。\n而他手下的料理确是会说话的，一副生气勃勃的样子，个性鲜明。\n任何食材在他调教之下，都转化为华丽惊艳的佳肴，美味又不失食材本真，令品鉴者如沐春风。\n与之形成鲜明对照的，却是转化的过程：朴素、自然、简单。\n体魄强健，个性率真的Gorden Chen，愿将自己从业多年的体验与感受与众人分享，让致力于此的烹饪爱好者们都能体会生活的趣味和不可思议。','chef/chef/7s.jpg','chef/chef/7b.jpg','上海','7','1','Mr.Smile先生');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('8','FIGO','暂缺','虽然带着眼镜，文质彬彬，却是一个超级大体育迷。\n很难想象，一个在篝火旁烹饪的大厨有如此灿烂的笑容。他的笑容，虽然不一定是给食客，但是以一种乐观的心态烹饪出的菜肴当然会与众不同。\n对很多事务，他都有自己独到的见解，不盲从，不跟风。\n他把烹饪也看成是一种比赛，他说要将菲仕乐学院餐厅立足上海滩，成为意大利餐厅中的王者。\n即便躲在厨房看不见，但是不要紧，报名学院餐厅的课程，可以领略他的微笑阳光和个性鲜明的见解。','chef/chef/8s.jpg','chef/chef/8b.jpg','上海','8','1','阳光一样的笑容');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('9','Jerry','暂缺','Jerry是个笑眯眯的人，但是如果你想尝试动下他最常用的那把刀，你试试……\n他那娴熟流畅的技艺，犹如古龙笔下的刀客附体，干净利落的刀法，于波澜不惊处尽显深厚功力，令观者目眩神迷，啧啧称奇。尤其是当你看过他一秒不到的时间几下就捏出来的寿司，如魔术一样迷幻。\n在众多食客眼中，拥有20年餐饮集团及超五星级酒店的工作管理经验的Jerry Ke无疑就是中国的\"寿司之神\"。无论是如诗如画的料理，还是行云流水的寿司制作技艺，Jerry所要传递出的不仅是一份原汁原味的真，岁月静好的美，更是一份饱含禅意的待客之心。','chef/chef/9s.jpg','chef/chef/9b.jpg','上海','9','1','绕指间的艺术家');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('10','Randy','北京金融街威斯汀 厨师长\n北京柏悦酒店 副厨师长\n美国皇家加勒比邮轮公司  厨师/面点师','他的头很亮，浑身上下一尘不染，帅大叔一枚。不工作的时候去参加party，竟然也会带一个耳钉，兼具时髦与传统。\n如果你去北京菲仕乐学院餐厅就餐，会看到他忙得脚步不停。\n他为人谦和，你问他一个问题，他会微微弯腰，不厌其烦地告诉你。是不是当家的人都这样？\n胸前插着一只温度计，时刻准备检查食物的温度，确保达到最好的效果。\n看似是个喜欢忙碌的人，他又说，自己最爱读书，可见动静相宜，都是他的菜。\n那么漂亮的餐厅，必须得有这么一个人在管事，才最最放心，也最最适宜。','chef/chef/10s.jpg','chef/chef/10b.jpg','北京','10','1','一个永远闲不下来的行政总厨');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('11','荣誉','北京励骏酒店  法餐副厨师长\nMAISON BOULUD米其林二星法餐厅  西厨房主管\n北京国航万丽酒店西餐 厨师','他很喜欢笑，从不着急的一副样子。\n他说，他最大的缺点就是脾气太好，哪怕心里急，也表现不出来。可是作为一个要求那么高的厨师长，内心一定十分的纠结。\n为了维持对美味的正确把握，他烟酒不沾，这点，十分难得。\n他说，北京学院餐厅的这个团队实在是太好了，身为一个管理者，对工作有这样的肯定更加难得。\n说着说着他又去检查餐具是否清洁了，真是眼里永远有活的男人。','chef/chef/11s.jpg','chef/chef/11b.jpg','北京','11','1','我最大的缺点和优点都是脾气太好了');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('12','王伟','北京嘉里中心饭店  行政主厨/厨师长\n北京东方君悦大酒店  西餐冷菜主管','他说自己没脾气，然后别人听到了，反驳说，他其实脾气很大。\n估计没脾气，是他的理想，而有脾气，却是现状。\n身为要求很高的厨师长，怎么可以没有脾气。然后别人又说，他控制得有分寸。\n他站在那里，不怒自威，一个标准的北京爷们，有但当，够负责。\n他说，北京学院餐厅提供的菜肴是五星酒店都达不到的高水准，根据他从业的经历看来，他说的这句话可圈可点，可信度十足。','chef/chef/12s.jpg','chef/chef/12b.jpg','北京','12','1','标准北京爷们');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('13','刘淼','北京开源名都大酒店  高级厨师\n北京威斯汀大酒店    一级厨师\n北京万豪大酒店      二级厨师','北京城里，意大利匹萨做得最好的人之一，就是他。\n有两道浓眉，看似十分有个性，但他却是个特别有礼貌的人。\n烤出的匹萨出神入化，看得出食客很喜欢，而他本人对此也相当的骄傲。问到烤炉上那个跟火山一样的LOGO，他也回答得头头是道。\n无论做什么，他都很细致入微，这样的人，却说自己的缺点没耐心？！\n只要对厨艺有耐心就足够了。','chef/chef/13s.jpg','chef/chef/13b.jpg','北京','13','1','好吃的匹萨诞生于礼貌与耐心');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('14','吴争','北京柏悦酒店 领班\n北京香港马会会所 领班\n鑫海锦江大酒店 厨师','他爱好广泛，尤其喜欢猫，喜欢猫的男人都很善良。\n和他名字一样，是一个与世无争，性格很好的人。\n他有一个很大的块头，在后厨房灵活移动，根本停不下来，忙中有序。他最擅长意大利菜，尤其是扒式菜肴，喜欢吃牛扒的人可以好好跟他请教。\n他说，世界上只有两种人可以穿白大褂，一个是医生，一个就是厨师，一种施加帮助，一种施加幸福。\n他很喜欢这份工作，他说他一直憧憬有一份光明的未来，言语之间，可以感受到他的真诚，我们相信他一定能够实现。','chef/chef/14s.jpg','chef/chef/14b.jpg','北京','14','1','我憧憬有光明的未来');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('15','杜帅','北京香港马会会所 厨师\n北京四季酒店 厨师','问他，为啥要选择这一行，他说，我从小就馋，喜欢吃，所以就选择这行啦。\n在自行车之都，他说，他是个简单的人，没有过多的想法，但有一个梦想，就是未来开一家以自行车为主题的餐厅。把最爱的两样事务相结合，那岂不是世间最美妙的一件事？\n看得出来，他十分喜欢骑车。轻轻松松，一天上百公里，对他真的不是难事。\n身为九零后，他身上特点鲜明，没有过多的想法，但是目标鲜明，知道自己要什么。\n这样的人，做出的匹萨不仅好吃，也带有自己的个性呢，您值得亲赴学院餐厅一试。','chef/chef/15s.jpg','chef/chef/15b.jpg','北京','15','1','想开自行车主题餐厅的厨师');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('16','胡彬','星期五餐饮有限公司 厨房管理','喜欢音乐，当过乐队主唱。\n喜欢骑车，跟杜帅一起，加入专业的俱乐部，一日骑行上百公里。他说，骑行的时候是他最放松的时候。\n喜欢厨师这个行业，在星期五一做就是做了十一年。\n他是无论干什么都喜欢做到极致的人。\n高兴的时候，他会给你看他的纹身，纹于三十岁，是一条鱼跃过龙门，变成金龙。\n这代表他的梦想，先脚踏实地，再出人头地。','chef/chef/16s.jpg','chef/chef/16b.jpg','北京','16','1','曾当过乐队主场的大厨');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('17','康兵','park plaza 厨师\n名人酒店  厨师','康师傅做的是面条，而康兵兵做的是冷菜。\n随和，好接触，他这么形容自己。\n他说：我就是喜欢做饭。他特别享受自己做的食物被人夸奖，视为职业荣誉。\n他微信上发的都是对厨师这个行业的领悟，他是个有追求的人。细细碎碎，看似平常，却有一种仪式感，令人感动。\n他有一个美满的家庭，相信这也是他奋斗的工作动力。\n在菲仕乐学院餐厅，康师傅就是一种有责任的厨师代表。','chef/chef/17s.jpg','chef/chef/17b.jpg','北京','17','1','别人叫我康师傅');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('18','贺超','北京丽思卡尔顿酒店  西餐热菜厨师\n希尔顿酒店  冷菜中级厨师','他给人感觉很像一座塔，高大，踏实地矗立在那里，给人很有安全感。\n看着如此强壮的一个男人，却有一颗敏感、纤细的心。\n他十分喜欢学院餐厅这个团队，说就跟他家里人一样。这是对自己工作的地方最大的赞美吧。\n他对家里人很看重，微信上是他夫人的照片，时刻捧在手里。\n一个如此热爱工作的人，他做的菜也带着情感，端上菲仕乐学院餐厅的餐桌，如诗如画般绽放在您的眼前。','chef/chef/18s.jpg','chef/chef/18b.jpg','北京','18','1','这个团队就跟我家人一样');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('19','李翰','北京兆龙饭店厨师/面点师','要跟他成为朋友，他才愿意讲很多话给你听。但即便不熟悉，也可以感受到他是个很容易开心的人。\n那么大的个子，喜欢堆模型，把成百上千块模型拼成一个成品，很有成就感。相信在堆积模型的时候，凡间万千烦恼都化作云消。\n厨师，真的是一门需要静心做的艺术。因为揉面不到位，匹萨就不会好吃。\n但李翰臣可以做到揉到最合适的时候。他对面团的专注，有跟对待模型一般的玲珑心思。','chef/chef/19s.jpg','chef/chef/19b.jpg','北京','19','1','好厨师都需要能静心');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('20','孝伟','励骏酒店 pastry sour chef\n昆泰嘉华酒店  面包房主管\n凯宾斯基酒店  厨师','一米八的一个大男人，做提拉米苏的时候，是那么小心翼翼，那么专注。\n可是他却说，厨师这行是他当时误打误撞进来的，中考报名，没考虑很多就这么报了，没想到就一直这么干了下去。像不像很多人的人生道路，充满了偶然，却也充满了必然。\n只有专注，方可做到极致，果然他说，他把提拉米苏这道菜做到极致，人人都发自内心地说好吃就是他追求的目标。\n目标看似就在方寸之间，可是这方寸之地，亦可称王者。','chef/chef/20s.jpg','chef/chef/20b.jpg','北京','20','1','误打误撞走入这行的西点专家');
insert into {$this->getTable('d1m_chef')} (`chef_id`, `cname`, `cshort`, `clong`, `csmallpic`, `cbigpic`, `cregion`, `corder`, `cstatus`, `coneword`) values('21','周强','北京万豪酒店  意大利餐厅厨房主管','问他在学院餐厅印象最深的一件事，竟然不是关于自己的，而是亲眼看到匹萨大师Enzo Coccia为他们授课，他说，那种风度风范让他向往，他会梦想有朝一日也成为那样的大师。\n他是有天分的，据说他学习一天可以追上别人几周的工作效果，一周可以追上别人几个月，美食的天赋令人惊艳。\n对这样的夸耀，他却悄悄解释说：我以前学过类似的。真的是一个诚实的人。\n可是对美食不诚实，做东西又怎么会好吃呢？\n他说：将来我也想成为这个领域的大师。\n让我们拭目以待。','chef/chef/21s.jpg','chef/chef/21b.jpg','北京','21','1','做匹萨是一种天赋');

";

$installer->run($sql);
$installer->endSetup();
?>
