<div class="dashboard">
	<div class="page-title">
	    <h1><?php echo $this->__('Edit Account Information') ?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
	    <div class="fieldset">
	        <?php echo $this->getBlockHtml('formkey')?>
	        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
	        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	        <ul class="form-list">
	            
	            <li class="form-item">
	                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
	            </li>
	
	            <li class="control">
	                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
	            </li>
	        </ul>
	    </div>
	    <div class="fieldset"  style="display:none;" id="change2" name="change2">
	        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
	        <ul class="form-list">
	            <li class="form-item">
					<label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
					<!-- This is a dummy hidden field to trick firefox from auto filling the password -->
					<input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
				</li>
	            <li class="fields">
	                <div class="field form-item">
	                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
	                    <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
	                </div>
	                <div class="field form-item">
	                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
	                    <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
	                </div>
	            </li>
	        </ul>
	    </div>
	    <div class="buttons-set">	        
	        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
			<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	    </div>
	</form>
    <div class="hint"><?php echo $this->__('if you want to change the mobile number %s , please contact with the customer service',$this->getCustomer()->getPhone()); ?></div>
</div>
<script type="text/javascript">
    //<![CDATA[
    function setPasswordForm(arg)
    {

            if (arg) $('#change2').show();else $('#change2').hide();
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>