<div class="dashboard" style="background-color:#fff;padding:20px;margin-top:80px;">
	<div class="page-title">
	    <h1><?php echo $this->__('Edit Account Information') ?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
	    <div class="fieldset">
	        <?php echo $this->getBlockHtml('formkey')?>
	        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
	        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	        <ul class="form-list">
	            
	            <li>
	                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                <div class="input-box">
	                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
	                </div>
	            </li>

                <li>
                    <label for="phone" class="required"><em>*</em><?php echo $this->__('手机号') ?></label>
                    <div class="input-box">
                        <input type="phone" autocapitalize="off" autocorrect="off" spellcheck="false" name="phone" id="phone" value="<?php echo $this->escapeHtml($this->getCustomer()->getPhone()) ?>" title="<?php echo $this->__('手机号') ?>" class="input-text required-entry" />
                    </div>
                </li>

                <li class="form-item verification">
                    <label for="verification">验证码</label>
                    <div class="input-box">
                        <input name="verification" id="verification" type="text" value="">
                     </div>
                    <div class="send-code">获取验证码</div>
                </li>


	
	            <li class="control">
	                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
	            </li>
	        </ul>
	    </div>
	    <div class="fieldset" style="display:;">
	        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
	        <ul class="form-list">
	            <li>
	                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
	                <div class="input-box">
	                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
	                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
	                </div>
	            </li>
	            <li class="fields">
	                <div class="field">
	                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
	                    <div class="input-box">
	                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
	                    </div>
	                </div>
	                <div class="field">
	                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
	                    <div class="input-box">
	                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
	                    </div>
	                </div>
	            </li>
	        </ul>
	    </div>
	    <div class="buttons-set">
	        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
	    </div>
	</form>
</div>